services:

  frontend:
    build: ./eurgence/
    ports:
      - "3000:3000"
    volumes:
      -  ./eurgence/frontend/:/app

  backend:
    build: ./eurgence/
    ports:
      - "8000:8000"
    volumes:
      - ./eurgence/backend/:/app

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./eurgence/workshop/frontend/public/index.html:/usr/share/nginx/html
    depends_on:
      - db
      - frontend
      - backend
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workshop
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
              